//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector_sample_OBJ.KFTDataInjector {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeKFTReturn", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TypeKFTReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool isSuccesfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isSuccesful {
            get {
                return this.isSuccesfulField;
            }
            set {
                if ((this.isSuccesfulField.Equals(value) != true)) {
                    this.isSuccesfulField = value;
                    this.RaisePropertyChanged("isSuccesful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TypeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtProviderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtSerialCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        private System.DateTime SrcDateTimeField;
        
        private byte StoryInfoField;
        
        private byte ST_StatusField;
        
        private byte NS_GpsQualityField;
        
        private byte FlagsField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private int AltitudeField;
        
        private short SpeedField;
        
        private short DirectionField;
        
        private uint InputValidField;
        
        private uint InputValueField;
        
        private uint FunValidField;
        
        private uint FunValueField;
        
        private uint OutputValidField;
        
        private uint OutputValueField;
        
        private short NumAnalogValidField;
        
        private uint AnalogValue0Field;
        
        private uint AnalogValue1Field;
        
        private uint AnalogValue2Field;
        
        private uint AnalogValue3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtProviderName {
            get {
                return this.ExtProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtProviderNameField, value) != true)) {
                    this.ExtProviderNameField = value;
                    this.RaisePropertyChanged("ExtProviderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtSerialCode {
            get {
                return this.ExtSerialCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtSerialCodeField, value) != true)) {
                    this.ExtSerialCodeField = value;
                    this.RaisePropertyChanged("ExtSerialCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime SrcDateTime {
            get {
                return this.SrcDateTimeField;
            }
            set {
                if ((this.SrcDateTimeField.Equals(value) != true)) {
                    this.SrcDateTimeField = value;
                    this.RaisePropertyChanged("SrcDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public byte StoryInfo {
            get {
                return this.StoryInfoField;
            }
            set {
                if ((this.StoryInfoField.Equals(value) != true)) {
                    this.StoryInfoField = value;
                    this.RaisePropertyChanged("StoryInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public byte ST_Status {
            get {
                return this.ST_StatusField;
            }
            set {
                if ((this.ST_StatusField.Equals(value) != true)) {
                    this.ST_StatusField = value;
                    this.RaisePropertyChanged("ST_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public byte NS_GpsQuality {
            get {
                return this.NS_GpsQualityField;
            }
            set {
                if ((this.NS_GpsQualityField.Equals(value) != true)) {
                    this.NS_GpsQualityField = value;
                    this.RaisePropertyChanged("NS_GpsQuality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public byte Flags {
            get {
                return this.FlagsField;
            }
            set {
                if ((this.FlagsField.Equals(value) != true)) {
                    this.FlagsField = value;
                    this.RaisePropertyChanged("Flags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public short Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public short Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((this.DirectionField.Equals(value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public uint InputValid {
            get {
                return this.InputValidField;
            }
            set {
                if ((this.InputValidField.Equals(value) != true)) {
                    this.InputValidField = value;
                    this.RaisePropertyChanged("InputValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public uint InputValue {
            get {
                return this.InputValueField;
            }
            set {
                if ((this.InputValueField.Equals(value) != true)) {
                    this.InputValueField = value;
                    this.RaisePropertyChanged("InputValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public uint FunValid {
            get {
                return this.FunValidField;
            }
            set {
                if ((this.FunValidField.Equals(value) != true)) {
                    this.FunValidField = value;
                    this.RaisePropertyChanged("FunValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public uint FunValue {
            get {
                return this.FunValueField;
            }
            set {
                if ((this.FunValueField.Equals(value) != true)) {
                    this.FunValueField = value;
                    this.RaisePropertyChanged("FunValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public uint OutputValid {
            get {
                return this.OutputValidField;
            }
            set {
                if ((this.OutputValidField.Equals(value) != true)) {
                    this.OutputValidField = value;
                    this.RaisePropertyChanged("OutputValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public uint OutputValue {
            get {
                return this.OutputValueField;
            }
            set {
                if ((this.OutputValueField.Equals(value) != true)) {
                    this.OutputValueField = value;
                    this.RaisePropertyChanged("OutputValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public short NumAnalogValid {
            get {
                return this.NumAnalogValidField;
            }
            set {
                if ((this.NumAnalogValidField.Equals(value) != true)) {
                    this.NumAnalogValidField = value;
                    this.RaisePropertyChanged("NumAnalogValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public uint AnalogValue0 {
            get {
                return this.AnalogValue0Field;
            }
            set {
                if ((this.AnalogValue0Field.Equals(value) != true)) {
                    this.AnalogValue0Field = value;
                    this.RaisePropertyChanged("AnalogValue0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public uint AnalogValue1 {
            get {
                return this.AnalogValue1Field;
            }
            set {
                if ((this.AnalogValue1Field.Equals(value) != true)) {
                    this.AnalogValue1Field = value;
                    this.RaisePropertyChanged("AnalogValue1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public uint AnalogValue2 {
            get {
                return this.AnalogValue2Field;
            }
            set {
                if ((this.AnalogValue2Field.Equals(value) != true)) {
                    this.AnalogValue2Field = value;
                    this.RaisePropertyChanged("AnalogValue2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public uint AnalogValue3 {
            get {
                return this.AnalogValue3Field;
            }
            set {
                if ((this.AnalogValue3Field.Equals(value) != true)) {
                    this.AnalogValue3Field = value;
                    this.RaisePropertyChanged("AnalogValue3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KFTDataInjector.KFTDataInjectorSoap")]
    public interface KFTDataInjectorSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginWithResponse", ReplyAction="*")]
        Connector_sample_OBJ.KFTDataInjector.LoginWithResponseResponse LoginWithResponse(Connector_sample_OBJ.KFTDataInjector.LoginWithResponseRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Connector_sample_OBJ.KFTDataInjector.LoginResponse Login(Connector_sample_OBJ.KFTDataInjector.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name LogoutResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        Connector_sample_OBJ.KFTDataInjector.LogoutResponse Logout(Connector_sample_OBJ.KFTDataInjector.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name isLoginDoneResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isLoginDone", ReplyAction="*")]
        Connector_sample_OBJ.KFTDataInjector.isLoginDoneResponse isLoginDone(Connector_sample_OBJ.KFTDataInjector.isLoginDoneRequest request);
        
        // CODEGEN: Generating message contract since element name AllStories from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertKFTStoryData", ReplyAction="*")]
        Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataResponse InsertKFTStoryData(Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginWithResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginWithResponse", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.LoginWithResponseRequestBody Body;
        
        public LoginWithResponseRequest() {
        }
        
        public LoginWithResponseRequest(Connector_sample_OBJ.KFTDataInjector.LoginWithResponseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginWithResponseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginWithResponseRequestBody() {
        }
        
        public LoginWithResponseRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginWithResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginWithResponseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.LoginWithResponseResponseBody Body;
        
        public LoginWithResponseResponse() {
        }
        
        public LoginWithResponseResponse(Connector_sample_OBJ.KFTDataInjector.LoginWithResponseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginWithResponseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn LoginWithResponseResult;
        
        public LoginWithResponseResponseBody() {
        }
        
        public LoginWithResponseResponseBody(Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn LoginWithResponseResult) {
            this.LoginWithResponseResult = LoginWithResponseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Connector_sample_OBJ.KFTDataInjector.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Connector_sample_OBJ.KFTDataInjector.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(Connector_sample_OBJ.KFTDataInjector.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogoutRequestBody {
        
        public LogoutRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(Connector_sample_OBJ.KFTDataInjector.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn LogoutResult;
        
        public LogoutResponseBody() {
        }
        
        public LogoutResponseBody(Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isLoginDoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isLoginDone", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.isLoginDoneRequestBody Body;
        
        public isLoginDoneRequest() {
        }
        
        public isLoginDoneRequest(Connector_sample_OBJ.KFTDataInjector.isLoginDoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class isLoginDoneRequestBody {
        
        public isLoginDoneRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isLoginDoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isLoginDoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.isLoginDoneResponseBody Body;
        
        public isLoginDoneResponse() {
        }
        
        public isLoginDoneResponse(Connector_sample_OBJ.KFTDataInjector.isLoginDoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isLoginDoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn isLoginDoneResult;
        
        public isLoginDoneResponseBody() {
        }
        
        public isLoginDoneResponseBody(Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn isLoginDoneResult) {
            this.isLoginDoneResult = isLoginDoneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKFTStoryDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKFTStoryData", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataRequestBody Body;
        
        public InsertKFTStoryDataRequest() {
        }
        
        public InsertKFTStoryDataRequest(Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKFTStoryDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.TypeInfo[] AllStories;
        
        public InsertKFTStoryDataRequestBody() {
        }
        
        public InsertKFTStoryDataRequestBody(Connector_sample_OBJ.KFTDataInjector.TypeInfo[] AllStories) {
            this.AllStories = AllStories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKFTStoryDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKFTStoryDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataResponseBody Body;
        
        public InsertKFTStoryDataResponse() {
        }
        
        public InsertKFTStoryDataResponse(Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKFTStoryDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn InsertKFTStoryDataResult;
        
        public InsertKFTStoryDataResponseBody() {
        }
        
        public InsertKFTStoryDataResponseBody(Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn InsertKFTStoryDataResult) {
            this.InsertKFTStoryDataResult = InsertKFTStoryDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KFTDataInjectorSoapChannel : Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KFTDataInjectorSoapClient : System.ServiceModel.ClientBase<Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap>, Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap {
        
        public KFTDataInjectorSoapClient() {
        }
        
        public KFTDataInjectorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KFTDataInjectorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KFTDataInjectorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KFTDataInjectorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connector_sample_OBJ.KFTDataInjector.LoginWithResponseResponse Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap.LoginWithResponse(Connector_sample_OBJ.KFTDataInjector.LoginWithResponseRequest request) {
            return base.Channel.LoginWithResponse(request);
        }
        
        public Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn LoginWithResponse(string UserName, string Password) {
            Connector_sample_OBJ.KFTDataInjector.LoginWithResponseRequest inValue = new Connector_sample_OBJ.KFTDataInjector.LoginWithResponseRequest();
            inValue.Body = new Connector_sample_OBJ.KFTDataInjector.LoginWithResponseRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            Connector_sample_OBJ.KFTDataInjector.LoginWithResponseResponse retVal = ((Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap)(this)).LoginWithResponse(inValue);
            return retVal.Body.LoginWithResponseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connector_sample_OBJ.KFTDataInjector.LoginResponse Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap.Login(Connector_sample_OBJ.KFTDataInjector.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string UserName, string Password) {
            Connector_sample_OBJ.KFTDataInjector.LoginRequest inValue = new Connector_sample_OBJ.KFTDataInjector.LoginRequest();
            inValue.Body = new Connector_sample_OBJ.KFTDataInjector.LoginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            Connector_sample_OBJ.KFTDataInjector.LoginResponse retVal = ((Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connector_sample_OBJ.KFTDataInjector.LogoutResponse Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap.Logout(Connector_sample_OBJ.KFTDataInjector.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn Logout() {
            Connector_sample_OBJ.KFTDataInjector.LogoutRequest inValue = new Connector_sample_OBJ.KFTDataInjector.LogoutRequest();
            inValue.Body = new Connector_sample_OBJ.KFTDataInjector.LogoutRequestBody();
            Connector_sample_OBJ.KFTDataInjector.LogoutResponse retVal = ((Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap)(this)).Logout(inValue);
            return retVal.Body.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connector_sample_OBJ.KFTDataInjector.isLoginDoneResponse Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap.isLoginDone(Connector_sample_OBJ.KFTDataInjector.isLoginDoneRequest request) {
            return base.Channel.isLoginDone(request);
        }
        
        public Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn isLoginDone() {
            Connector_sample_OBJ.KFTDataInjector.isLoginDoneRequest inValue = new Connector_sample_OBJ.KFTDataInjector.isLoginDoneRequest();
            inValue.Body = new Connector_sample_OBJ.KFTDataInjector.isLoginDoneRequestBody();
            Connector_sample_OBJ.KFTDataInjector.isLoginDoneResponse retVal = ((Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap)(this)).isLoginDone(inValue);
            return retVal.Body.isLoginDoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataResponse Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap.InsertKFTStoryData(Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataRequest request) {
            return base.Channel.InsertKFTStoryData(request);
        }
        
        public Connector_sample_OBJ.KFTDataInjector.TypeKFTReturn InsertKFTStoryData(Connector_sample_OBJ.KFTDataInjector.TypeInfo[] AllStories) {
            Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataRequest inValue = new Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataRequest();
            inValue.Body = new Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataRequestBody();
            inValue.Body.AllStories = AllStories;
            Connector_sample_OBJ.KFTDataInjector.InsertKFTStoryDataResponse retVal = ((Connector_sample_OBJ.KFTDataInjector.KFTDataInjectorSoap)(this)).InsertKFTStoryData(inValue);
            return retVal.Body.InsertKFTStoryDataResult;
        }
    }
}
